### PR TITLE
Update version of the Snyk CLI to v1.790.0

### PR DESCRIPTION
**Pull request by glours**
Signed-off-by: Guillaume Lours <guillaume.lours@docker.com>

**- What I did**
Upgrade Snyk CLI and Docker image to version `v1.790.0` 
Upgrade Go version to `1.17.5`
Use `--app-vulns` for all scans and add the `--experiment` flag when used in combination with `--json` flag

**- A picture of a cute animal (not mandatory)**
image

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like there's still a diff in `go.sum` (perhaps another `go mod tidy` is needed?);

```
#14 [check-go-mod 1/1] RUN scripts/validate/check-go-mod
#14 sha256:2e723009db3bcac90312e5281dc84f0ba8b78ec801c3e7d6020f7a8bfe60f904
#14 0.538 
#14 0.538 These files were changed:
#14 0.538 
#14 0.538  M go.sum
```

**Review by StefanScherer — APPROVED** [review]
LGTM
Tested it locally on a Intel Mac with and without json output.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Pull request merged**
