### PR TITLE
Create initial config file if not on win/mac (managed by Desktop) 

### PR DESCRIPTION
**Pull request by gtardif**
**- What I did**
* if not on win/mac (Docker Desktop), check if config file already exists and if not create an empty one
* rebased on top of #136 to be able to test this all

*Only the last commit is added here, previous commits are from #136* 

Fixes https://github.com/docker/scan-cli-plugin/issues/138

This is the same as #139, but not pushed on a fork for CI reasons

**- How I did it**

**- How to verify it**
* remove the scan config file and  `~/.docker/scan` folder
* try `docker scan nginx` 

**- Description for the changelog**

**- A picture of a cute animal (not mandatory)**

### CODE REVIEW

**Comment by gtardif** [comment]
Checked with @glours, linux version is a bit higher than the desktop one dues to linux login fix. Desktop version can be sync in a follow up PR

**Comment by gtardif** [comment]
started mac/windows tests manually to ensure they pass before we merge this, and I did well: https://github.com/docker/scan-cli-plugin/runs/2093843627?check_suite_focus=true

to confirm @glours @silvin-lubecki : 
on Desktop, we can assume we'll never use snyk docker image, and we should test this mode only on linux (with no snyk binary installed)?

**Comment by glours** [comment]
@gtardif yes! At least for the moment, Docker Desktop should use the embedded Snyk version or the one defined in the user PATH (if there is one obviously)

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Comment by gtardif** [comment]
still some issue with multi-platform tests : https://github.com/docker/scan-cli-plugin/actions/runs/645849829... looking at this

**Comment by gtardif** [comment]
Still stuck with red linux tests (https://github.com/docker/scan-cli-plugin/runs/2096691120?check_suite_focus=true) 
(but I reproduce the error message on a linux machine and the last commit does fix it, removing the mkdir and the error is back 🤔 )
And now https://github.com/docker/scan-cli-plugin/runs/2096814916?check_suite_focus=true#step:6:67
`You have reached your pull rate limit. You may increase the limit by authenticating and upgrading`... 
Will get back on this after the WE I think

**Comment by glours** [comment]
Let's squash-merge to clean the commit history 😅

**Pull request merged**
