### PR TITLE
Update to Go 1.17.5

### PR DESCRIPTION
**Pull request by thaJeztah**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory)**

### CODE REVIEW

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Comment by glours** [comment]
Please I making a [PR](https://github.com/docker/scan-cli-plugin/pull/182) which upgrade all our dependencies right now to check the whole integrity of the CLI at once.
This PR will conflict with mine

**Review by StefanScherer — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Closing in favor of https://github.com/docker/scan-cli-plugin/pull/182 👍

**Pull request closed without merging**
